version: '3'

services:
  db:
    image: tsp/db
    restart: always
    env_file:
      ./db/bin/db.env
    ports:
      - 27017:27017
    volumes:
      - ./db/bin/db.init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./db/data:/data/db
  server:
    image: tsp/server
    restart: always
    ports:
      - 3001:3001
    links:
      - db
  web-client:
    image: tsp/web-client
    restart: always
    ports:
      - 3000:3000
    links:
      - server
