version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    volumes:
      - ./bin/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 4321:4321
