version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      ./bin/db.env
    ports:
      - 5432:5432
    volumes:
      - ./bin/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 4321:4321
