version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      ./bin/db.env
    ports:
      - 27017:27017
    volumes:
      - ./bin/db.init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data-dev:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
      ME_CONFIG_MONGODB_URL: mongodb://dev:dev@mongo:27017/
